routes/html.py
from flask import Blueprint, render_template, redirect, url_for
from db import db
from models import Order, Customer, Product
# Creates a Blueprint object (similar to Flask). Make sure you give it a name!
html_bp = Blueprint("html", __name__)

@html_bp.route("/")
def homepage():
    return render_template("home.html", name="Aaron")

@html_bp.route("/customer")
def customers():
    statement = db.select(Customer).order_by(Customer.name)
    records = db.session.execute(statement)
    customers = records.scalars().all()
    return render_template("customers.html", customers=customers)
@html_bp.route("/customer/<int:customer_id>")
def get_customer(customer_id):
    customer = Customer.query.get_or_404(customer_id)
    if customer:
        return render_template("customerInfo.html",customerOrders=customer.orders)
    else:
        return "Customer not found", 404    
@html_bp.route("/products")
def products():
    statement = db.select(Product).order_by(Product.name)
    records = db.session.execute(statement)
    products = records.scalars().all()
    return render_template("products.html", products=products)

@html_bp.route("/orders")
def orders():
    statement = db.select(Order).order_by(Order.id)
    records = db.session.execute(statement)
    orders = records.scalars().all()
    return render_template("orders.html", orders=orders)

@html_bp.route("/orders/<int:order_id>")
def get_order(order_id):
    orders = Order.query.get_or_404(order_id)
    total = orders.get_total()
    return render_template("orderInfo.html",orders=orders, total=total)

@html_bp.route("/orders/<int:order_id>/process", methods=["POST"])
def process_order(order_id):
    order = Order.query.get_or_404(order_id)
    order.process()
    return redirect(url_for("html.orders"))
@html_bp.route("/<int:order_id>/delete", methods=["POST"])
def order_delete(order_id):
    order = Order.query.get_or_404(order_id)
    if order.processed:
        return "Order has been already processed", 418
    db.session.delete(order)
    db.session.commit()
    return redirect(url_for("html.orders"))

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
    <body>
        <div class="header">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
              <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('html.homepage') }}"><img src="{{ url_for('static', filename='3514981.jpg')}}" alt="" width="100px" height="100px"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{{ url_for('html.homepage') }}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('html.customers') }}">Customers</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('html.products') }}">Products</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('html.orders') }}">Orders</a>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>
          </div>
        {% block content %}
        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

templates/customerInfo.html
{% extends "base.html" %}

{% block content %}
<div>
    <table class="table table-striped">
      <thread>
        <th scope="col">#</th>
        <th scope="col">OrderId</th>
        <th scope="col">Order Total</th>
        <th scope="col">Process</th>

      </thread>
      <tbody>
        {% for order in customerOrders %}
          <tr>
            <th scope="row">{{loop.index0}}</th>
            <td><a href="{{ url_for('html.get_order', order_id=order.id) }}">{{order.id}}</a></td>
            <td>{{order.get_total()}}</td>
            <td>{{order.processed}}</td>
          </tr>
          {% endfor %}
      </tbody>

    </table>
</div>
{% endblock %}

templates/customers.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h1>Customers</h1>
    <table class="table table-striped">
      <thread>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Phone</th>
        <th scope="col">Balance</th>
      </thread>
      <tbody>
        {% for customer in customers %}
          <tr>
            <th scope="row">{{loop.index0}}</th>
            <td><a href="{{ url_for('html.get_customer', customer_id=customer.id) }}">{{customer.name}}</a></td>
            <td>{{customer.phone}}</td>
            <td>{{customer.balance}}</td>
          </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{{ url_for('static', filename='bread.jpg')}}" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{{ url_for('static', filename='roastchicken.jpg')}}" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{{ url_for('static', filename='snowflakeApple.jpg')}}" alt="Third slide">
      </div>
    </div>
  </div>
{% endblock %}

templates/orderInfo.html
{% extends "base.html" %}

{% block content %}
<div>
    <table class="table table-striped">
        <thread>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
        </thread>
        <tbody>
            {% for product in orders.items %}
            <tr>
              <th scope="row">{{loop.index0}}</th>
              <td>{{ product.product.name}}</td>
              <td>{{ product.product.price }}</td>
              <td>{{ product.quantity }}</td>
            </tr>
            {% endfor %}
        </tbody>
  
      </table>
      <ul class="list-group">
        <li class="list-group-item disabled">Est. Total: {{total}}</li>
        <li class="list-group-item">Customer Name: {{ orders.customer.name }}</li>
        <li class="list-group-item">Order Created: {{ orders.created }}</li>
        <li class="list-group-item">Order Processed: {{ orders.processed }}</li>
      </ul>
      <div class="btn-group" role="group" aria-label="Basic example">
        <form action="{{ url_for('html.process_order', order_id=orders.id) }}" method="POST">
          <button type="submit" class="btn btn-primary {% if orders.processed %}disabled{% endif %}" {% if orders.processed %}disabled{% endif %}>
            {% if orders.processed %}
              Order Processed
            {% else %}
              Process Order
            {% endif %}
          </button>
        </form>
        
        <form method="POST" action="{{ url_for('html.order_delete', order_id=orders.id) }}">
          <button class="btn btn-warning {% if orders.processed %}disabled{% endif %}" {% if orders.processed %}disabled{% endif %}" type="submit">Delete</button>
        </form>
      </div>
      
</div>
{% endblock %}

templates/orders.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h1>Orders</h1>
    <table class="table table-striped">
      <thread>
        <th scope="col">#</th>
        <th scope="col">Order Id</th>
        <th scope="col">Customer Name</th>
      </thread>
      <tbody>
        {% for order in orders %}
          <tr>
            <th scope="row">{{loop.index0}}</th>
            <td><a href="{{ url_for('html.get_order', order_id=order.id) }}">{{order.id}}</a></td>
            <td><a href="{{ url_for('html.get_customer', customer_id=order.customer.id) }}">{{order.customer.name}}</a></td>

          </tr>
          {% endfor %}
      </tbody>

    </table>
  </div>

{% endblock %}

templates/products.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h1>Products</h1>
    <table class="table table-striped">
      <thread>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
      </thread>
      <tbody>
        {% for product in products %}
          <tr>
            <th scope="row">{{loop.index0}}</th>
            <td>{{product.name}}</td>
            <td>{{product.price}}</td>
            <td>{{product.available}}</td>
          </tr>
          {% endfor %}
      </tbody>

    </table>
  </div>

{% endblock %}